# RSS 订阅源配置文件
# 这个文件定义了RSS订阅源列表，全局设置请在VS Code插件设置中配置

version: "1.0"

# RSS订阅源列表
feeds:
  - id: example-tech
    name: 技术博客示例
    url: https://example.com/rss.xml
    enabled: false
    updateInterval: 60
    tags: []
    description: ''
  - id: "github-releases-example"
    name: "GitHub 发布示例"
    url: "https://github.com/microsoft/vscode/releases.atom"
    enabled: false
    updateInterval: 180
    tags: ["开发工具", "更新"]
    description: "一个 GitHub 发布通知的示例"

# 全局设置请在VS Code插件设置中配置：
# - issueManager.rss.autoUpdate: 是否自动更新
# - issueManager.rss.defaultUpdateInterval: 默认更新间隔
# - issueManager.rss.maxItemsPerFeed: 每个订阅源最大文章数
# - issueManager.rss.enableNotifications: 是否启用通知
